.github/workflows/ci.yml, Dockerfile, Procfile, config/gunicorn.conf.py, portal/settings.py, requirements.txt
- Dockerfile
- Procfile
- gunicorn configuration that will bind to cabotage unix socket
I also set the Django database to configure from a DATABASE_URL environment variable using dj-database-url
This also requires adding whitenoise to serve static files, which may not be suitable for development.
=> add basics for cabotage

.gitignore, Makefile, compose.yml, readme.md
This is all fairly boiler plate and _does_ work but may need adjustments to suit your needs down the line.
Closes #26
=> setup for local dev using docker

portal/settings.py
this was causing admin assets not to render.
=> actually install whitenoise

portal/settings.py
Obtain the value from the environment variable.
=> Add the DEFAULT_FROM_EMAIL setting

.github/FUNDING.yml
Create a funding yml file for direct sponsorship to PyLadiesCon fund.
=> Add Funding.yml

portal/forms.py, portal/settings.py
Closes https://github.com/pyladies/pyladiescon-portal/issues/40
We can also change the label of last_name to preferred name or something
=> Exposed first name and last name at signup

templates/portal/base.html
Related to https://github.com/pyladies/pyladiescon-portal/issues/34
Preview on all pages
=> Added banner to all pages

portal_account/views.py, templates/portal_account/index.html, templates/portal_account/portalprofile_detail.html, templates/portal_account/portalprofile_edit.html, templates/portal_account/portalprofile_form.html
=> feat: Allow editing the portal profile

templates/volunteer/index.html, templates/volunteer/volunteerprofile_detail.html, templates/volunteer/volunteerprofile_form.html, volunteer/forms.py, volunteer/views.py
=> feat: Allow editing the volunteer profile

compose.yml
=> Add postgres volume

templates/portal/base.html
=> feat: Add opengraph tags to base html template

templates/volunteer/volunteerprofile_form.html
fix: #111 
updated language selection form:
=> feat: Improved language selection form

volunteer/forms.py
=> feat: sort language selection form alphabetically

CONTRIBUTING.md, docs/developer/contributing.md, docs/developer/setup.md
Resolves #133
- Creates a CONTRIBUTING.md 
- Edits the contributing and setup guides with information about forking (instead of cloning) the repo to get started
=> Add CONTRIBUTING.md

docs/developer/setup.md
Code blocks need to be unindented,
and can be tagged with what language they represent.
=> Fixed a bug with the code blocks.

docs/developer/setup.md
Updated the setup.md to include the information on how to solving cairo missing library on Mac.
fix #138
=> Update troubleshoot 

templates/volunteer/volunteerprofile_form.html, volunteer/forms.py, volunteer/models.py
https://github.com/pyladies/pyladiescon-portal/issues/122
Update the form to add help text for each of the fields.
It also fixes a couple bugs.
=> 112 updates to the volunteer sign up

docs/developer/howto.md, docs/developer/setup.md, portal/settings.py, readme.md
- Updated the database in the project settings: previously was using sqlite as backend
- Removes the duplicated content present on the readme.md and links to the live documentation.
- Update both the setup.md and the howtos.md to account for development without docker
Closes: #135
=> Fixes: #135 Add instructions for developing locally without docker

docs/developer/howto.md
Related: #41 and #157 
Fixes: #158
=> Adds translation instructions

Dockerfile, Makefile, docs/developer/howto.md
- Adds gettext to docker image
- Updates makefile to add translations commands. Fixes: #160
- Adjusts translation documentation to support docker commands
=> Adds translation support in docker

templates/portal/base.html, templates/portal/index.html, templates/volunteer/email/volunteer_profile_email_notification.html, templates/volunteer/email/volunteer_profile_email_notification.txt, templates/volunteer/index.html, templates/volunteer/volunteerprofile_form.html, volunteer/forms.py
=> Update landing page messaging

docs/developer/contributing.md, docs/developer/howto.md, docs/policies/acceptable_use_policy.md, docs/user/get_started.md, docs/user/sponsor.md, docs/user/volunteer.md, templates/account/signup.html
=> Fix broken urls

portal/validators.py, tests/volunteer/test_forms.py, tests/volunteer/test_models.py, volunteer/forms.py, volunteer/models.py
Just check if it starts with linked in domain to allow people to submit their profiles.
=> Relax LinkedIn Url check
